service: product-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: Allow
      Action: sqs:*
      Resource: !GetAtt SQSQueue.Arn
    - Effect: Allow
      Action: sns:*
      Resource:
        Ref: SNSTopic

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue

    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic

    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: Pavel_Lichmaniuk@epam.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic

plugins:
  - serverless-webpack

functions:
  getProductsList:
    environment:
      PG_HOST: lesson4-instance.chy5ntpppatx.eu-west-1.rds.amazonaws.com
      PG_PORT: 5432
      PG_DATABASE: lesson4
      PG_USERNAME: postgres
      PG_PASSWORD: d8HJCCpvS50qHHTqBzr0
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  catalogBatchProcess:
    environment:
      PG_HOST: lesson4-instance.chy5ntpppatx.eu-west-1.rds.amazonaws.com
      PG_PORT: 5432
      PG_DATABASE: lesson4
      PG_USERNAME: postgres
      PG_PASSWORD: d8HJCCpvS50qHHTqBzr0
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            !GetAtt SQSQueue.Arn
  getProductsById:
    environment:
      PG_HOST: lesson4-instance.chy5ntpppatx.eu-west-1.rds.amazonaws.com
      PG_PORT: 5432
      PG_DATABASE: lesson4
      PG_USERNAME: postgres
      PG_PASSWORD: d8HJCCpvS50qHHTqBzr0
    handler: handler.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
  createProduct:
    environment:
      PG_HOST: lesson4-instance.chy5ntpppatx.eu-west-1.rds.amazonaws.com
      PG_PORT: 5432
      PG_DATABASE: lesson4
      PG_USERNAME: postgres
      PG_PASSWORD: d8HJCCpvS50qHHTqBzr0
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
